spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.0.219:3306/consultation?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: zsy
    password: 123456
  mvc:
    format:
      date: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  servlet:
    encoding:
      charset: utf-8
  port: 8088

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml, classpath:/mybatis/mapper/extend/*.xml

logging:
  level:
    com.example.mybatisplus.mapper: debug
file-upload-path: ./file
