spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/consultation?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  mvc:
    format:
      date: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  servlet:
    encoding:
      charset: utf-8
  port: 8088

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml, classpath:/mybatis/mapper/extend/*.xml

logging:
  level:
    com.example.mybatisplus.mapper: debug
file-upload-path: ./file

test:
  sms:
#    accessKeyId: LTAI5t7rv2eV4KdoNacCrDzm
#    accessKeySecret: GvCJB2nfeo72Z3cNm6bHYLuDvX1BGr
    signName: 学生心理咨询平台
    templateCode: SMS_468770282
    templateCode2: SMS_468510335
    rigon: cn-hangzhou
